# Generated by Django 4.2.3 on 2023-09-09 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='is_client',
            field=models.BooleanField(default=False),
        ),
    ]
