# Generated by Django 4.2.3 on 2023-10-07 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_leadfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='lead_files'),
        ),
    ]
