# Generated by Django 4.2.6 on 2023-11-26 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_initial'),
        ('client', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='leads.lead'),
        ),
    ]
