# Generated by Django 4.2.3 on 2023-09-16 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_alter_client_team'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ('name', 'created_by')},
        ),
    ]
