# Generated by Django 4.2.6 on 2023-11-18 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_emailsettings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmailSettings',
            new_name='EmailSetting',
        ),
    ]
