# Generated by Django 4.2.3 on 2023-09-16 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='nembers',
            new_name='members',
        ),
    ]
