# Generated by Django 4.2.6 on 2023-10-14 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_room_messages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='manager',
            new_name='agent',
        ),
    ]
