# Generated by Django 4.2.3 on 2023-10-07 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
