# Generated by Django 4.2.6 on 2023-10-15 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_clientfile'),
        ('userprofile', '0005_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.client'),
        ),
    ]
