# Generated by Django 4.2.6 on 2023-11-18 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_alter_ticket_ticket_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-created_at', 'priority', 'ticket_number']},
        ),
    ]
